language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DTOML_BUILD_EXAMPLE=ON && make